language: r
os: linux
dist: xenial
cache: packages
warnings_are_errors: true
r_build_args: '--compact-vignettes="gs+qpdf"'
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual
jobs:
  include:
    - r: 3.5.0
      r_packages:
        - ape
        - bookdown
        - kdensity
        - pkgload
        - phangorn
        - Rdpack
        - rmarkdown
        - roxygen2
        - testthat
        - tinytex
        - usethis
        - vdiffr
        - devtools
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      r_binary_packages:
       - ape
       - covr
       - devtools
       - knitr
       - phangorn
       - pkgload
       - Rdpack
       - roxygen2
       - testthat
       - usethis
      r_packages:
       - bookdown
       - kdensity
       - vdiffr
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on: 
          branch: master
    - r: devel
      r_binary_packages:
       - covr
       - devtools
       - knitr
       - phangorn
       - pkgload
       - Rdpack
       - roxygen2
       - testthat
       - usethis
      r_packages:
       - ape
       - bookdown
       - kdensity
       - vdiffr
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      r: release
      r_packages:
        - ape
        - bookdown
        - kdensity
        - phangorn
        - pkgload
        - Rdpack
        - roxygen2
        - testthat
        - usethis
        - vdiffr
        - devtools
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref
  allow_failures:
    r: 3.5.0 # TreeSearch requires > 3.5.0

git:
  depth: 1

 
r_github_packages:
 - ms609/TreeTools
 - ms609/TreeDist
 - ms609/TreeDistData


before_script:
  - R -e "pkgload::load_all(); devtools::document()"

notifications:
  email:
    on_success: change
    on_failure: change
