language: r
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual
matrix:
  include:
    - r: release
      after_success:
        - Rscript -e "covr::codecov()"
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - r: devel
    - os: osx
      r: 3.4.0
  allow_failures:
    r: devel # Incompatible with devtools

git:
  depth: 1

r_github_packages:
 - ms609/TreeSearch
 - ms609/TreeDistData
# - r-lib/pkgload
# - r-lib/devtools

r_packages:
 - bookdown
 - vdiffr
 
r_binary_packages:
 - ape
 - covr
 - devtools
 - phangorn
 - Rdpack
 - roxygen2
 - testthat

before_script:
  - R -e "devtools::document()"

notifications:
  email:
    on_success: change
    on_failure: change
